// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOPZ98oFqFTvbewdEzzHh5JcYpyMo8xqY',
    appId: '1:501054824114:web:9d3bf0eb49d4c55b23f3ab',
    messagingSenderId: '501054824114',
    projectId: 'breath-noise-d73d1',
    authDomain: 'breath-noise-d73d1.firebaseapp.com',
    storageBucket: 'breath-noise-d73d1.firebasestorage.app',
    measurementId: 'G-9QPF70G07R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkXZJFxmBDn-ktfB4MeG4hpScLyBZ1g24',
    appId: '1:501054824114:android:e34925a72ec2fa8d23f3ab',
    messagingSenderId: '501054824114',
    projectId: 'breath-noise-d73d1',
    storageBucket: 'breath-noise-d73d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGLJmyVJ890KORQ5WQr3atj5UBRyYypmU',
    appId: '1:501054824114:ios:878fc622fa9acdf323f3ab',
    messagingSenderId: '501054824114',
    projectId: 'breath-noise-d73d1',
    storageBucket: 'breath-noise-d73d1.firebasestorage.app',
    iosClientId: '501054824114-jfhg5u21kor1p13hkmgirjs3n6n3faeq.apps.googleusercontent.com',
    iosBundleId: 'com.breath.noise',
  );

}